version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: erd_project
    container_name: erd_project-app-container
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: erd_project-app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./vendor:/var/www/vendor
      - ./storage:/var/www/storage
    ports:
      - "9000:9000"
    networks:
      - app-network
  web:
    image: nginx:alpine
    container_name: erd_project-nginx-container
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
